name: news_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
